name: "Gradle Assemble"
description: "Assembles a gradle project"
inputs:
  java-version:
    default: 21
    description: "Version of Java to build with"
  java-distribution:
    default: "temurin"
    description: "Distribution of Java to use"
  token:
    description: pat token
    required: true
outputs:
  jar-path:
    description: "path of the built jar file"
    value: ${{ steps.build-step.outputs.jar-path }}
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4.2.1
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      id: build-step
      run: |
        bash gradlew assemble
        echo "jar-path=$(find ./build/libs -iname '*.jar' ! -iname '*-dev*' | paste -sd '!')" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_USERNAME: strenkml
        GITHUB_TOKEN: ${{ inputs.token }}
